### ISSUE TITLE
Bot crashes when color is not in list

### ISSUE THREAD

**Issue by hansmariusoveras** [ESN-Trondheim/ESNbot#34]

**Comment by LaiAlexander** [comment]
![image](https://github.com/ESN-Trondheim/ESNbot/assets/680733/db8a13ad-837e-4502-b03e-4ea88f650c71)
Weird. I can't reproduce. It should just default to dark blue (#2e3192) if no color arguement is supplied or if the color doesn't match anything in the list.

**Comment by LaiAlexander** [comment]
The actual reason for the crash here was probably what is outlined in #57. It's fixed in the master branch now, with PR #59
